columns:
  age: float
  bp: float
  sg: float
  al: float
  su: float
  rbc: category
  pc: category
  pcc: category
  ba: category
  bgr: float
  bu: float
  sc: float
  sod: float
  pot: float
  hemo: float
  pcv: float
  wbcc: float
  rbcc: float
  htn: category
  dm: category
  cad: category
  appet: category
  pe: category
  ane: category

numerical_columns:
  - age: float
  - bp: float
  - sg: float
  - al: float
  - su: float
  - bgr: float
  - bu: float
  - sc: float
  - sod: float
  - pot: float
  - hemo: float
  - pcv: float
  - wbcc: float
  - rbcc: float

categorical_columns:
  - rbc: category
  - pc: category
  - pcc: category
  - ba: category
  - htn: category
  - dm: category
  - cad: category
  - appet: category
  - pe: category
  - ane: category


target_column: class





  



