columns:
  age: float
  bp: float
  sg: float
  al: float
  su: float
  rbc: category
  pc: category
  pcc: category
  ba: category
  bgr: float
  bu: float
  sc: float
  sod: float
  pot: float
  hemo: float
  pcv: category
  wc: category
  rc: category
  htn: category
  dm: category
  cad: category
  appet: category
  pe: category
  ane: category
  class: category

numerical_columns:
  - age
  - bp
  - sg
  - al
  - su
  - bgr
  - bu
  - sc
  - sod
  - pot
  - hemo
  - rc
  - pcv 
  - wc 
   

categorical_columns:
  - rbc
  - pc
  - pcc
  - ba
  - htn
  - dm
  - cad
  - appet
  - pe
  - ane


target_column: class





  



